Safe creation
rsksmart/safe-core-sdk pull request #1
Opened 2021-05-13 12:41 UTC by antomor

Remove the deployment of the proxy factory and tests improvement

2021-05-13 12:43 UTC, antomor commented
I still have some doubts about what I could check upon successful EthersSafe creation.

2021-05-13 20:24 UTC, ilanolkies commented on tests/creation.test.ts
> +      chai.expect(safeSdk).not.to.be.undefined
We can check for example
```suggestion
      chai.expect(await safeSdk.getOwners()).to.be.eq(owners)
      chai.expect(await safeSdk.getThreshold()).to.be.eq(2)
```

2021-05-13 20:31 UTC, ilanolkies requested changes

2021-05-13 20:31 UTC, ilanolkies commented on src/EthersSafeFactory.ts
> +  constructor(signer: Signer, safeProxyConfiguration: SafeProxyFactoryConfiguration) {
I would just get `proxyFactoryAddress` and `safeSingletonAddress` on the constructor. Then, accept `data`, `nonce` and `callbackAddress` as method arguments

2021-05-13 20:31 UTC, ilanolkies commented on src/EthersSafeFactory.ts
> +  threshold?: number
I would put this as required param (based on what you must choose in the UI outside _advanced_)

2021-05-13 20:31 UTC, ilanolkies commented on src/EthersSafeFactory.ts
> +  async createSafe(safeAccountConfiguration: SafeAccountConfiguration): Promise<Safe> {
```suggestion
  async createSafe(safeAccountConfiguration: SafeAccountConfiguration, deploymentOptions: {
    data: string,
    nonce?: number,
    callbackAddress?: string
  }): Promise<Safe> {
```

2021-05-18 13:41 UTC, ilanolkies approved these changes

2021-05-18 13:41 UTC, merged